### ISSUE TITLE
v1.1.3 broken caching of virtualenv

### ISSUE THREAD

**Issue by peterbe** [snok/install-poetry#29]
Our use case is as follows:
```
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python poetry
        uses: snok/install-poetry@v1.1.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: yari/deployer/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install deployer
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd yari/deployer
          poetry install
```
But when we got [upgraded to version v1.1.3](https://github.com/mdn/content/pull/4155) it broke things. 

```
The virtual environment found in /home/runner/work/content/content/yari/deployer/.venv seems to be broken.
Recreating virtualenv deployer in /home/runner/work/content/content/yari/deployer/.venv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deployer'
```
Full run here: https://github.com/mdn/content/runs/2359767214?check_suite_focus=true

We've never had this problem with v1.1.2 before. 

The `poetry install` takes 10 seconds so it was nice to be able to cache it.

**Comment by sondrelg** [comment]
Thanks for the report @peterbe!

I'll see if I'm able to replicate this later today if I can. In the meantime, could you try to invalidate your cache by changing this line:

```
key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
```

to this:

```
key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-1
```

and running it twice more?

**Comment by peterbe** [comment]
That's a great idea! It could manually type the version of the action in there.
